#!/bin/bash
set -e

# This command will authorise credentials. Exit status 0 indicates correct credentials, any other exit status indicates otherwise.
# We also use this file to set up a fake backend 'project'.

project="$RUN_ENV/projects/$PROJECT_NAME"
if [ -d "$project" ]
then
  echo 'Credentials correct'
  exit 0
fi

echo "Creating project '$PROJECT_NAME'"
mkdir -p "$project"

nodes_dir="$project/nodes"
detailed_nodes_dir="$project/detailed_nodes"
dirs=("$nodes_dir" "$detailed_nodes_dir")

for dir in "${dirs[@]}"
do
  mkdir "$dir"
done

echo "Creating login1.yaml..."
for dir in "${dirs[@]}"
do
  cat <<EOF > "$dir/login1.yaml"
---
type: compute_small
name: login1
region: Mars
provider: example-provider
currency: "bottled sparkling water"
price_per_hour: 1
state: on
tags:
    - type: compute_small
EOF
done
cat <<EOF >> "$detailed_nodes_dir/login1.yaml"
cpu: 2
gpu: 2
mem: 2
EOF

for int in {01..03}
do
  name="cnode$int"
  echo "Creating $name.yaml..."
  for dir in "${dirs[@]}"
  do
    cat <<EOF > "$dir/$name.yaml"
---
type: mining_rig
name: $name
region: Metaverse
provider: example-provider
currency: Bitcoin
price_per_hour: 0.000123
EOF
  done
  cat <<EOF >> "$detailed_nodes_dir/$name.yaml"
cpu: 1
gpu: 8192
mem: 8.1632
EOF
done

echo 'Credentials correct'
