#!/usr/bin/env bash

set -e

# This command will authorise credentials. Exit status 0 indicates correct credentials, any other exit status indicates otherwise.
# We also use this file to set up a fake backend 'project'.

if [ "$PROJECT_NAME" == "invalid" ]
then
  echo '{"result": false}'
  exit 0
fi

project="$RUN_ENV/projects/$PROJECT_NAME"
if [ -d "$project" ]
then
  echo '{"result": true}'
  exit 0
fi

mkdir -p "$project"

nodes_dir="$project/nodes"
mkdir "$nodes_dir"

cat <<EOF > "$nodes_dir/login1.yaml"
---
instance_id: login1
model: compute_small
region: Mars
state: on
tags:
  type: compute
  compute_group: example_group
EOF

for int in {01..03}
do
  name="cnode$int"

  cat <<EOF > "$nodes_dir/$name.yaml"
---
instance_id: $name
model: mining_rig
region: Metaverse
state: on
tags:
  type: compute
  compute_group: example_group
EOF
done

echo '{"result": true}'
