#!/usr/bin/env bash
set -e

# Get cost of instance(s) between two dates, as a float
#
# Vars:
# START_TIME: Unix timestamp
# END_TIME: Unix timestamp
# INSTANCE_IDs: IDs to get cost for, comma separated list
# PROJECT_NAME: provided credential

# Calculate date range
TIME_DIFF=$(echo "$END_TIME-$START_TIME" | bc)
DIFF_IN_HOURS=$(echo "$TIME_DIFF/60/60" | bc -l)
UPTIME=$(echo "$DIFF_IN_HOURS * 0.6" | bc -l) # Assume an average uptime of 60%

IFS=',' read -ra ids_array <<< "$INSTANCE_IDS"

# Initialise final output variable as empty YAML object
export out="---"

# Very convoluted method of injecting yq merge into ids_array
for instance in "${ids_array[@]}"
do
  # Fetch instance type
  TYPE=$("$RUN_ENV/bin/yq_linux_amd64" '.model' "$RUN_ENV/projects/$PROJECT_NAME/nodes/$instance.yaml")

  CURRENCY=$("$RUN_ENV/bin/yq_linux_amd64" '.financial_data.currency' "$RUN_ENV/instance_models/$TYPE.yaml")

  # Fetch hourly price of instance type
  HOURLY_COST=$("$RUN_ENV/bin/yq_linux_amd64" '.financial_data.price_per_hour' "$RUN_ENV/instance_models/$TYPE.yaml")
  INSTANCE_COST=$(echo "$UPTIME * $HOURLY_COST" | bc -l)
  
  FINANCIAL_DATA=$("$RUN_ENV/bin/yq_linux_amd64" -n "with(.;.currency = \"$CURRENCY\" | .price = \"$INSTANCE_COST\")")

  ECO_PERSPECTIVE=$("$RUN_ENV/bin/yq_linux_amd64" '.eco_data.perspective' "$RUN_ENV/instance_models/$TYPE.yaml")

  ECO_UNIT=$("$RUN_ENV/bin/yq_linux_amd64" '.eco_data.unit' "$RUN_ENV/instance_models/$TYPE.yaml")

  # Fetch eco quantity of instance type
  ECO_QUANTITY=$("$RUN_ENV/bin/yq_linux_amd64" '.eco_data.quantity' "$RUN_ENV/instance_models/$TYPE.yaml")

  ECO_DATA=$("$RUN_ENV/bin/yq_linux_amd64" -n "with(.;.perspective = \"$ECO_PERSPECTIVE\" | .unit = \"$ECO_UNIT\" | .quantity = \"$ECO_QUANTITY\")")

  # Total cost for instance
  TOTAL_ECO_IMPACT=$(echo "$UPTIME * $KWH_USAGE" | bc -l)

  # Construct variable to store YAML for newly processed instance
  # Has to be exported so that yq can access it
  export new=$("$RUN_ENV/bin/yq_linux_amd64" -n "with(.; .instance_id = \"$instance\" | .financial_data = \"$FINANCIAL_DATA\" | .eco_data = \"$ECO_DATA\")")

  # Merge out-string and new instance string
  out=$("$RUN_ENV/bin/yq_linux_amd64" -n 'env(out) + [env(new)]')
done

"$RUN_ENV/bin/yq_linux_amd64" -n 'env(out)' -o=json
