#!/usr/bin/env bash

IFS=',' read -ra models <<< "$MODELS"

export out="---"

for model in "${models[@]}"
do
  export new=$("$RUN_ENV/bin/yq_linux_amd64" eval '.' "$RUN_ENV/instance_models/$model.yaml")
  out=$("$RUN_ENV/bin/yq_linux_amd64" -n 'env(out) + [env(new)]')
done

"$RUN_ENV/bin/yq_linux_amd64" -n 'env(out)' -o=json
