#!/usr/bin/env bash
set -e

# Get cost of instance(s) between two dates, as a float
#
# Vars:
# START_DATE: Unix timestamp
# END_DATE: Unix timestamp
# INSTANCE_ID: ID to get cost for
# PROJECT_NAME: provided credential

# Calculate date range
TIME_DIFF=$(echo "$END_DATE-$START_DATE" | bc)
DIFF_IN_HOURS=$(echo "$TIME_DIFF/60/60" | bc -l)
UPTIME=$(echo "$DIFF_IN_HOURS * 0.6" | bc -l) # Assume an average uptime of 60%


# Fetch instance type
TYPE=$("$RUN_ENV/bin/yq_linux_amd64" '.type' "$RUN_ENV/projects/$PROJECT_NAME/nodes/$INSTANCE_ID.yaml")


# Fetch hourly cost of instance type
HOURLY_COST=$("$RUN_ENV/bin/yq_linux_amd64" '.cost_per_hour' "$RUN_ENV/instance_types/$TYPE.yaml")


# Total cost for instance
INSTANCE_COST_PER_HOUR=$(echo "$UPTIME * $HOURLY_COST" | bc -l)

echo "$INSTANCE_COST_PER_HOUR"
