#!/usr/bin/env bash

# Calculate average and last usage, accurate to two decimal places
read -r average last <<< $(awk -v max=100 'BEGIN{srand(); printf "%.2f %.2f", rand()*max, rand()*max}')

# return the JSON string including the usage data
echo "{\"average\":\"$average\",\"last\":\"$last\"}"
