#!/usr/bin/env bash

sleep 1

# Calculate average and last usage, accurate to two decimal places
read -r average last <<< $(awk -v max=100 'BEGIN{srand(); printf "%.2f %.2f", rand()*max, rand()*max}')

# Start and end time could be fetched like this in practice
st=$START_TIME
et=$END_TIME

# return the JSON string including the usage data
echo "{\"instance_id\":\"$INSTANCE_ID\",\"average\":\"$average\",\"last\":\"$last\"}"
