#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

OUT="[]"

for model in $(echo "$MODELS" |sed 's/,/ /g') ; do

    # Get instance details
    instance_details=$(openstack flavor show $model -f json -c name -c ram -c vcpus |jq '. | { model: .name, cpu: .vcpus, mem: .ram }')

    # Get cost (fallback to columns 2 and 3 of fallback_model_details.txt if none)
    price=""
    if [ -z "$price" ] ; then
        price="$(grep "^$model" $DIR/fallback_model_details.txt |awk '{print $2}')"
        currency="$(grep "^$model" $DIR/fallback_model_details.txt |awk '{print $3}')"
    fi

    # Get carbon (fallback to clumn 4 of fallback_model_details.txt if none)
    carbon=""
    if [ -z "$carbon" ] ; then
        carbon="$(grep "^$model" $DIR/fallback_model_details.txt |awk '{print $4}')"
    fi

    # Add details to output
    out=$(echo "$instance_details" |jq ". += { \"provider\": \"openstack\", \"kilowatts_per_hour\": \"$carbon\", \"currency\": \"$currency\", \"price_per_hour\": \"$price\"}")

    # Add to array
    OUT="$(echo "$OUT" |jq ".[. |length] |= . + $out")"

done

echo "$OUT"
