#!/usr/bin/env bash

echo "Preparing..."

# Set up instance models and costs
echo "Creating instance models"
mkdir "$RUN_ENV/instance_models"
cat <<EOF > "$RUN_ENV/instance_models/compute_small.yaml"
---
model: compute_small
provider: example-provider
currency: GBP
price_per_hour: 1
cpu: 2
gpu: 2
mem: 2
EOF

cat <<EOF > "$RUN_ENV/instance_models/compute_large.yaml"
---
model: compute_large
provider: example-provider
currency: GBP
price_per_hour: 1.5
cpu: 4
gpu: 4
mem: 4
name: compute_large
cost_per_hour: 0.5
kilowatts_per_hour: 0.5
EOF

cat <<EOF > "$RUN_ENV/instance_models/mining_rig.yaml"
---
model: mining_rig
provider: example-provider
currency: Bitcoin
price_per_hour: 0.000123
cpu: 1
gpu: 8192
mem: 8.1632
=======
name: login
cost_per_hour: 0.1
kilowatts_per_hour: 0.2
EOF

cat <<EOF > "$RUN_ENV/instance_types/gpu.yaml"
---
name: gpu
cost_per_hour: 1
kilowatts_per_hour: 1
EOF

echo "Creating projects dir..."
mkdir "$RUN_ENV/projects"
echo "Created."

# Download yq for parsing YAML and JSON
echo "Downloading yq..."
mkdir "$RUN_ENV/bin"
wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -P "$RUN_ENV/bin"
chmod +x "$RUN_ENV/bin/yq_linux_amd64"
echo "Downloaded."

sleep 3
echo "Prepared."
