#!/usr/bin/env bash

echo "Preparing..."

# Set up instance models and costs
echo "Creating instance models"
mkdir "$RUN_ENV/instance_models"
cat <<EOF > "$RUN_ENV/instance_models/compute_small.yaml"
---
model: compute_small
provider: example-provider
currency: GBP
price_per_hour: 1
kilowatts_per_hour: 0.2
cpu: 2
gpu: 2
mem: 2
EOF

cat <<EOF > "$RUN_ENV/instance_models/compute_large.yaml"
---
model: compute_large
provider: example-provider
currency: GBP
price_per_hour: 1.5
kilowatts_per_hour: 0.5
cpu: 4
gpu: 4
mem: 4
EOF

cat <<EOF > "$RUN_ENV/instance_models/mining_rig.yaml"
---
model: mining_rig
provider: example-provider
currency: Bitcoin
price_per_hour: 0.000123
kilowatts_per_hour: 2
cpu: 1
gpu: 8192
mem: 8.1632
EOF

echo "Creating projects dir..."
mkdir "$RUN_ENV/projects"
echo "Created."

# Download yq for parsing YAML and JSON
mkdir "$RUN_ENV/bin"
echo "Downloading yq..."
wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -P "$RUN_ENV/bin"
chmod +x "$RUN_ENV/bin/yq_linux_amd64"
echo "yq downloaded."

# Download jq for constructing JSON
echo "Downloading jq..."
wget https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux-amd64 -P "$RUN_ENV/bin"
chmod +x "$RUN_ENV/bin/jq-linux-amd64"
echo "jq Downloaded."

sleep 3
echo "Prepared."
