#!/usr/bin/env bash

echo "Preparing..."

# Set up instance models and costs
echo "Creating instance models"
mkdir "$RUN_ENV/instance_models"
cat <<EOF > "$RUN_ENV/instance_models/compute_small.yaml"
---
model: compute_small
provider: example-provider
financial_data:
  currency: GBP
  price_per_hour: 1
eco_data:
  perspective: "energy_consumption"
  unit: kWh
  max_amount_per_hour: 0.2
cpu: 2
gpu: 2
mem: 2
EOF

cat <<EOF > "$RUN_ENV/instance_models/compute_large.yaml"
---
model: compute_large
provider: example-provider
financial_data:
  currency: GBP
  price_per_hour: 1.5
eco_data:
  perspective: "energy_consumption"
  unit: kWh
  max_amount_per_hour: 0.5
cpu: 4
gpu: 4
mem: 4
EOF

cat <<EOF > "$RUN_ENV/instance_models/mining_rig.yaml"
---
model: mining_rig
provider: example-provider
financial_data:
  currency: USD
  price_per_hour: 10.0123
eco_data:
  perspective: "carbon_emission"
  unit: kgCO2e
  max_amount_per_hour: 2
cpu: 1
gpu: 8192
mem: 8.1632
EOF

echo "Creating projects dir..."
mkdir "$RUN_ENV/projects"
echo "Created."

# Download yq for parsing YAML and JSON
mkdir "$RUN_ENV/bin"
echo "Downloading yq..."
wget https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -P "$RUN_ENV/bin"
chmod +x "$RUN_ENV/bin/yq_linux_amd64"
echo "Downloaded."

# Download bc for
echo "Downloading bc..."
curl "https://mirror.lyrahosting.com/gnu/bc/bc-1.07.1.tar.gz" -o "$RUN_ENV/bin/bc.tar.gz" -s
tar -xf "$RUN_ENV/bin/bc.tar.gz" -C "$RUN_ENV/bin"
cd "$RUN_ENV/bin/bc-1.07.1"
echo "Compiling bc..."
./configure -q
make >/dev/null 2>&1
echo "Removing compressed package..."
rm -rf "$RUN_ENV/bin/bc.tar.gz"
echo "bc prepared."

sleep 3
echo "Prepared."
